#!/bin/sh
## HT to Nuke! - https://github.com/kean/Nuke

set -eo pipefail

scheme="Asynchrone"

while getopts "s:d:" opt; do
    case $opt in
    	s) scheme=${OPTARG};;
      d) destination=$OPTARG;;
    esac
done
shift $((OPTIND -1))

echo "scheme = ${scheme}"
echo "destinations = ${destination}"

xcodebuild -version
xcodebuild build-for-testing -scheme "$scheme" -destination "$destination"

echo "\nRunning tests for destination: $destination"
xcodebuild test-without-building -scheme "$scheme" -destination "$destination"
