name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Default Scheme
        run: |
          scheme_list=$(xcodebuild -list -json | tr -d "\n")
          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
          echo $default | cat >default
          echo Using default scheme: $default
      - name: Test
        env:
          scheme: ${{ 'default' }}
          platform: ${{ 'OS X,arch=x86_64' }}
        run: |
          xcodebuild test -project Asynchrone.xcodeproj -scheme Asynchrone -destination 'platform=OS X,arch=x86_64'
