name: SwiftLint

on:
  pull_request:
    paths:
      - '.github/workflows/swiftlint.yml'
      - '.swiftlint.yml'
      - '**/*.swift'

jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - name: Swiftlint
        uses: norio-nomura/action-swiftlint@3.2.1
        with:
          args: --strict
        env:
          WORKING_DIRECTORY: Asynchrone
          DIFF_BASE: ${{ github.base_ref }}